# Site settings
title: "Jaewon Y"
email: "woniyoon@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://woniyoon.github.io" # the base hostname & protocol for your site

instagram_username: "yoonj1i"
github_username: "woniyoon"

# Build settings
markdown: kramdown
